/* eslint-disable no-underscore-dangle */
import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';

import axios from 'axios';
import { useQuery } from 'react-query';
import withAuthServerSideProps from 'src/hocs/withAuthGetServerSideProps';
import { useAuth } from 'src/hooks/auth/AuthContext';

import styles from '../../styles/Home.module.css';

const Home: NextPage = () => {
  const { userInfo, handleLogout } = useAuth();
  const result = useQuery('userInfo', () => axios.get('/api/user'));

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>ServerSide</h1>
        <h3>🙃Welcome {userInfo && userInfo.username}🙃</h3>
        <h1 className={styles.title}>ClientSide</h1>
        <h3>
          {result.isLoading && <>loading....</>}
          {result.isSuccess && (
            <>🙃Welcome {result.data && result.data.data.user.username}🙃</>
          )}
        </h3>
        <button type="button" onClick={handleLogout} className={styles.card}>
          <h4>로그아웃</h4>
        </button>
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = withAuthServerSideProps();
