/* eslint-disable no-underscore-dangle */
import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';

import withAuthServerSideProps from 'src/hocs/withAuthGetServerSideProps';
import { useAuth } from 'src/hooks/auth/AuthContext';

import styles from '../../styles/Home.module.css';

const Home: NextPage = () => {
  const { userInfo } = useAuth();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>🙃Welcome to {userInfo?.username}</h1>
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = withAuthServerSideProps();
